name: isoForam
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.24
  - matplotlib=3.7
  - scipy=1.10
  - netcdf4=1.6.2
  - cartopy=0.21
  - tqdm=4.64
  - unidecode=1.3
  - statsmodels=0.14