#! /usr/bin/env python3

species_lookup = {
	'B. digitata'                                     : 'Beella digitata',
	'B. pumilio'                                      : 'Berggrenia pumilio',
	'C. nitida'                                       : 'Candeina nitida',
	'D. anfracta'                                     : 'Dentigloborotalia anfracta',
	'G. calida'                                       : 'Globigerina calida',
	'G. crassaformis'                                 : 'Globigerina crassaformis',
	'G. elongatus'                                    : 'Globigerinoides elongatus',
	'G. falconensis'                                  : 'Globigerina falconensis',
	'G. glutinata'                                    : 'Globigerina glutinata',
	'G. radians'                                      : 'Globigerina radians',
	'G. ruber white'                                  : 'Globigerinoides ruber white',
	'G. rubescens'                                    : 'Globigerina rubescens',
	'G. scitula'                                      : 'Globorotalia scitula',
	'G. siphonifera'                                  : 'Globigerina siphonifera',
	'G. tenellus'                                     : 'Globigerinoides tenellus',
	'G. ungulata'                                     : 'Globorotalia ungulata',
	'H. pelagica'                                     : 'Hastigerina pelagica',
	'N. incompta'                                     : 'Neogloboquadrina incompta',
	'T. clarkei'                                      : 'Turborotalita clarkei',
	'T. fleisheri'                                    : 'Tenuitellita fleisheri',
	'T. humilis'                                      : 'Truncatulina humilis',
	'T. iota'                                         : 'Tenuitellita iota',
	'T. parkerae'                                     : 'Tenuitellita parkerae',
	'T. quinqueloba'                                  : 'Turborotalita quinqueloba',
	'Amphistegina lessoni'                            : 'Amphistegina lessoni',
	'Amphisterigina radiata'                          : 'Amphistegina radiata',
	'Amphistegina radiata'                            : 'Amphistegina radiata',
	'Bulimina marginata'                              : 'Bulimina marginata',
	'Cibicides lobatus'                               : 'Cibicidoides lobatus',
	'Cibicides wuellerstorfi'                         : 'Cibicidoides wuellerstorfi',
	'Cibicidoides wuellerstorfi'                      : 'Cibicidoides wuellerstorfi',
	'Cibicidoides'                                    : 'Cibicidoides',
	'Cibicidoides mundulus'                           : 'Cibicidoides mundulus',
	'Cibicidoides pachyderma'                         : 'Cibicidoides pachyderma',
	'Globigerina bulloides'                           : 'Globigerina bulloides',
	'G. bulloides'                                    : 'Globigerina bulloides',
	'G. conglobatus'                                  : 'Globigerinoides conglobatus',
	'Globigerinoides conglobatus'                     : 'Globigerinoides conglobatus',
	'Globorotalia hirsuta'                            : 'Globorotalia hirsuta',
	'G. hirsuta'                                      : 'Globorotalia hirsuta',
	'G. inflata'                                      : 'Globorotalia inflata',
	'Globorotalia inflata'                            : 'Globorotalia inflata',
	'Globorotalia menardii'                           : 'Globorotalia menardii',
	'Globorotalia menardii menardi'                   : 'Globorotalia menardii',
	'G. menardii'                                     : 'Globorotalia menardii',
	'G. menardii menardi'                             : 'Globorotalia menardii',
	'G. ruber'                                        : 'Globigerinoides ruber white',
	'G. ruber pink'                                   : 'Globigerinoides ruber pink',
	'Globigerinoides ruber pink'                      : 'Globigerinoides ruber pink',
	'Globigerinoides ruber white'                     : 'Globigerinoides ruber white',
	'G. ruber white s.l.'                             : 'Globigerinoides ruber white',
	'G. ruber white s.s.'                             : 'Globigerinoides ruber white',
	'G. truncatulinoides'                             : 'Globorotalia truncatulinoides',
	'G. truncatulinoides (d.)'                        : 'Globorotalia truncatulinoides (d.)',
	'G. truncatulinoides (s.)'                        : 'Globorotalia truncatulinoides (s.)',
	'Globorotalia truncatulinoides'                   : 'Globorotalia truncatulinoides',
	'G. tumida'                                       : 'Globorotalia tumida',
	'Globorotalia tumida'                             : 'Globorotalia tumida',
	'Globigerina bulloides'                           : 'Globigerina bulloides',
	'Globigerina glutinata'                           : 'Globigerina glutinata',
	'Globigerinoides ruber [coarse]'                  : 'Globigerinoides ruber white',
	'Globigerinoides ruber [fine]'                    : 'Globigerinoides ruber white',
	'Globigerinoides ruber white'                     : 'Globigerinoides ruber white',
	'Globigerinoides sacculifer'                      : 'Trilobatus sacculifer',
	'Globigerinoides trilobus [coarse]'               : 'Trilobatus trilobus',
	'Globigerinoides trilobus [fine]'                 : 'Trilobatus trilobus',
	'Globorotalia inflata [coarse]'                   : 'Globorotalia inflata',
	'Globorotalia inflata [fine]'                     : 'Globorotalia inflata',
	'Globorotalia truncatulinoides (d.) [coarse]'     : 'Globorotalia truncatulinoides (d.)',
	'Globorotalia truncatulinoides (d.) [fine]'       : 'Globorotalia truncatulinoides (d.)',
	'Globorotalia truncatulinoides (s.) [coarse]'     : 'Globorotalia truncatulinoides (s.)',
	'Globorotalia truncatulinoides (s.) [fine]'       : 'Globorotalia truncatulinoides (s.)',
	'Globorotalia truncatulinoides (d.)'              : 'Globorotalia truncatulinoides (d.)',
	'Globorotalia truncatulinoides (s.)'              : 'Globorotalia truncatulinoides (s.)',
	'Hoeglundina elegans'                             : 'Hoeglundina elegans',
	'Lenticulina convergens'                          : 'Lenticulina convergens',
	'Lenticulina iota'                                : 'Lenticulina iota',
	'Lenticulina spp'                                 : 'Lenticulina',
	'Lenticulina'                                     : 'Lenticulina',
	'Melonis barleannum'                              : 'Melonis barleannum',
	'Melonis spp'                                     : 'Melonis',
	'Melonis'                                         : 'Melonis',
	'Neogloboquadrina dutertrei'                      : 'Neogloboquadrina dutertrei',
	'N. dutertrei'                                    : 'Neogloboquadrina dutertrei',
	'N. pachyderma'                                   : 'Neogloboquadrina pachyderma',
	'Neogloboquadrina incompta'                       : 'Neogloboquadrina incompta',
	'N. pachyderma (d.)'                              : 'Neogloboquadrina incompta',
	'N. pachyderma (s.)'                              : 'Neogloboquadrina pachyderma',
	'Neogloboquadrina pachyderma (s.)'                : 'Neogloboquadrina pachyderma',
	'Neogloboquadrina pachyderma'                     : 'Neogloboquadrina pachyderma',
	'O. universa'                                     : 'Orbulina universa',
	'Orbulina universa'                               : 'Orbulina universa',
	'Oridorsalus umbonatus'                           : 'Oridorsalus umbonatus',
	'P. obliquiloculata'                              : 'Pulleniatina obliquiloculata',
	'Pulleniatina obliquiloculata'                    : 'Pulleniatina obliquiloculata',
	'Planulina ariminensis'                           : 'Planulina ariminensis',
	'Planulina foveolata'                             : 'Planulina foveolata',
	'Pyrgo serrata'                                   : 'Pyrgo serrata',
	'Pyrgo spp'                                       : 'Pyrgo',
	'Pyrgo'                                           : 'Pyrgo',
	'T. sacculifer'                                   : 'Trilobatus sacculifer',
	'T. trilobus'                                     : 'Trilobatus trilobus',
	'Trilobatus sacculifer'                           : 'Trilobatus sacculifer',
	'Trilobatus trilobus'                             : 'Trilobatus trilobus',
	'Uvigerina'                                       : 'Uvigerina',
	'Uvigerina curticosta'                            : 'Uvigerina curticosta',
	'Uvigerina flintii'                               : 'Uvigerina flintii',
	'Uvigerina mediterranea'                          : 'Uvigerina mediterranea',
	'Uvigerina peregrina'                             : 'Uvigerina peregrina',
	'Bulimina aculeata'                               : 'Bulimina aculeata',
	}

for s in list(species_lookup.values()):
	species_lookup[s] = s

if __name__ == '__main__':

	from csv import DictReader

	with open('../1_compile_D47_data/foram_D47_compilation.csv') as f:
		D47data = list(DictReader(f))

	with open('../2_compile_d18O_data/foram_d18O_compilation.csv') as f:
		d18Odata = list(DictReader(f))

	print('species_lookup = {')
	for s in sorted({r['Species'] for r in D47data + d18Odata}):
		print(f"	{repr(s):<50}: '{s}',")
	print('	}')


